version: '3.7'
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - 'redis_data:/bitnami/redis/data'
  api:
    container_name: icem-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: icem-api:latest
    ports:
      - '8081:8081'
    environment:
      - TZ=Asia/Bangkok

volumes:
  redis_data:
    driver: local