version: '3.7'
services:
  api:
    container_name: icem-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: icem-api:latest
    ports:
      - '8081:8081'
    environment:
      - TZ=Asia/Bangkok